### ISSUE TITLE
vuex로 적용후 '/:eventId' 사용하는 toUrl문제

### ISSUE THREAD

**Issue by jeean-irmina** [capstone-jicos/ongi-front#30]
eventId나 venueId를 사용해 page이동을 시키는 것들은 vuex적용시에 Id를 어떻게 해결해야 하는가??

**AS-IS**  Id사용하는 부분 제외하고는 다 가능

**Comment by lkaybob** [comment]
만약에 이동하는 페이지들의 URL에 `:eventId`가 있게 된다면, Vuex는 필요없고, `this.$route.params.eventId` 이렇게 추출해서 사용할 수 있어. 그렇지 않다면, `store/index.js`에 새로운 모듈을 정의해서 사용해야할 것이고. (현재 상황에 맞게 선택!)
