### ISSUE TITLE
createEvent에서 주소 지정

### ISSUE THREAD

**Issue by jeean-irmina** [capstone-jicos/ongi-front#31]
**AS-IS** googlemaps 미적용, vuex도 미적용

**To-Be** googlemaps적용 후 vuex적용

**Comment by lkaybob** [comment]
Google Maps의 경우에는 이전에 설치해둔 `vue-google-maps`를 사용하면 되긴 하는데, ([예시](https://github.com/capstone-jicos/ongi-front/blob/master/src/views/events/Info.vue#L45)) `:center`를 지정할 때는 `lat`, `lng` 값이 `null`이 들어가면 에러 뿜어내니까 초기값으로 숫자를 꼭 넣어줘야해 ([참고](https://github.com/capstone-jicos/ongi-front/blob/master/src/views/events/Info.vue#L88))
